### ISSUE TITLE
running rpmvenv twice - second time fails to overwrite existing rpm

### ISSUE THREAD

**Issue by bialix** [kevinconway/rpmvenv#105]
```
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.s9DD3M
+ umask 022
+ cd /tmp/rpmvenvzfest6gh/BUILD
+ rm -rf /tmp/rpmvenvzfest6gh/BUILDROOT/python-smoker-1.2.3-1.x86_64
+ exit 0
Traceback (most recent call last):
  File "/home/bialix/.local/bin/rpmvenv", line 8, in <module>
    sys.exit(main())
  File "/home/bialix/.local/lib/python3.6/site-packages/rpmvenv/cli.py", line 142, in main
    args['verbose'],
  File "/home/bialix/.local/lib/python3.6/site-packages/rpmvenv/cli.py", line 78, in generate_rpm
    shutil.move(pkg, destination)
  File "/usr/lib64/python3.6/shutil.py", line 548, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path './python-smoker-1.2.3-1.x86_64.rpm' already exists
```

Maybe proper error message would be better than traceback.

**Comment by kevinconway** [comment]
It's possible to change `rpmvenv` to delete or overwrite an existing file. The issue is that this has been default the behavior for so long that I wouldn't want to change it in case someone relies on it failing rather than overwriting.

Ideally, the tool would fail _before_ it does all the work rather than at the final step. The problem with this idea is that the RPM file name is not known until it is generated because the name is constructed by the `rpm` command. This is why there is not an existing check.

I think this problem mostly only affects folks who are trying out the project for the first time or doing a one-off, manual build of an RPM. I believe most folks who use this project do so in an automated environment like CI/CD. Because of that, I'm not likely to make any changes myself to improve this issue.

If this is an issue that will regularly affect you then I'd recommend doing something like:

- Add a new flag called `--destination-overwrite` that triggers the overwrite behavior. (See https://github.com/kevinconway/rpmvenv/blob/master/rpmvenv/cli.py#L44-L54 for flag examples)
-  Add a new CLI method called `overwrite_rpm` that works like [generate_rpm](https://github.com/kevinconway/rpmvenv/blob/master/rpmvenv/cli.py#L72-L79) but always deletes the destination before moving the binary.
- Use the new method instead of `generate_rpm` when the new flag is active.
- Add a test to the [CLI test suite](https://github.com/kevinconway/rpmvenv/blob/master/tests/test_cli.py) to validate the behavior.

That would be backwards compatible with existing features and prevent the stack trace. That's what I'd recommend if you wanted to put in a PR for this issue.
