### ISSUE TITLE
Is it possible to add post/preun block as content of python script?

### ISSUE THREAD

**Issue by bialix** [kevinconway/rpmvenv#114]
I would like to have post install block scriptlets to be my special python script executed. According to rpm docs there is option to execute arbitrary interpreter in %post %preun, e.g.

```
%post -p /usr/bin/python3
print("This is {} code".format("python"))
```

I just want to provide my script content somehow without writing it into rpmvenv.json line-by-line.

https://rpm-packaging-guide.github.io/#triggers-and-scriptlets
see section "Using Non-Shell Scripts in SPEC File"

Is it possible to achieve that in some [simple] way or my request requires heavy patching of your code?

**Comment by bialix** [comment]
Probably I can programmatically write my script into rpmvenv.json line-by-line with another python script, and insert it as list of strings into JSON. I'll try it.

**Comment by kevinconway** [comment]
If you plan to convert a script into lines of text for the rpmvenv.json then it should be as simple as copying over each line of code and escaping any double quote characters (`"`). This would include double escaping any quotes that are already escaped. For example, `echo "hello \"world\""` would become `echo \"hello \\"world\\"\"`. This only works for shell scripts because rpmvenv does not support using a different interpreter.

If you have a large script, or a non-shell script, and you only need to execute it after the package is installed, such as post or preun, then using the `files_extra` plugin is likely the easiest option. You install the script to some location such as `/opt/mypackage/scripts` (or anywhere else you think is appropriate) and then you add a post or preun line to your rpmvenv.json that executes that script like `/usr/bin/python3 /opt/mypackage/scripts/postinstall`. I have used this method in the past and especially to execute non-shell scripts.

Anything other than these two options will require a patch to support what you are trying to do.

**Comment by bialix** [comment]
I need such a script to properly support package upgrade. I think I just need to test how your approach will work in that case. Thanks.

**Comment by bialix** [comment]
> If you have a large script, or a non-shell script, and you only need to execute it after the package is installed, such as post or preun, then using the `files_extra` plugin is likely the easiest option. You install the script to some location such as `/opt/mypackage/scripts` (or anywhere else you think is appropriate) and then you add a post or preun line to your rpmvenv.json that executes that script like `/usr/bin/python3 /opt/mypackage/scripts/postinstall`. I have used this method in the past and especially to execute non-shell scripts.

The problem here is when running ``yum update package-new-version`` that script will be overriden by update, and therefore ``preun`` will be executed with already updated script not the old script. That could be a problem.

**Comment by kevinconway** [comment]
Happy to hear the workaround helped!
