### ISSUE TITLE
System dependencies

### ISSUE THREAD

**Issue by jripsl** [kevinconway/rpmvenv#26]
Hi,

I have a question regarding rpm dependencies.

My program needs following packages to be installed:

```
Requires:      gcc
Requires:      python >= 2.6
Requires:      python-pip
Requires:      python-devel
Requires:      openssl-devel
Requires:      sqlite
Requires:      sqlite-devel
Requires:      libxslt-devel
Requires:      libxml2-devel
Requires:      zlib-devel
Requires:      libffi-devel
```

Currently, I use a two steps procedure which is

1. generate the rpm package with rpmvenv,
2. edit the rpm SPEC file to add the 'Requires ..' lines, using 

```
rpmrebuild -pe <rpmfile>
```

but doing it in one step would be great.

Is it possible to specify those dependencies using the json file ?

**Comment by kevinconway** [comment]
*groan* I can't believe that isn't already part of this library. I seem to recall that being high on my mind when I started.

This is absolutely an addition that should be added to the `core` extension. Rather than annotate each line, I would suggest using the comma delimited notation for having multiple packages defined in requires. While we're at it we should likely add a `Provides` to balance out the `Requires`.

If you are interested in making this change I would encourage you to put up a pull request that modifies the `rpmvenv/extensions/core.py. Otherwise, I'll pick it up when I have the time. Thanks for pointing out this missing feature! It's a major one and should be included in the project.

**Comment by jripsl** [comment]
I made a pull request, but haven't tested it yet.
Will do asap.
Thanks

**Comment by kevinconway** [comment]
Excellent! I left some comments for you to review. I'm excited to have this feature in the project.

**Comment by jripsl** [comment]
Import fixed.
Now test fails with 'TypeError: Option must be an option type
I added option=StringOption, but it still fails on
" if not isinstance(option, opt.Option):"

**Comment by kevinconway** [comment]
Closing this ticket now that your patch is merged. PyPi version "0.13.0" has this feature now!

PR: https://github.com/kevinconway/rpmvenv/pull/30
