### ISSUE TITLE
prevent overwriting config files during upgrade

### ISSUE THREAD

**Issue by jripsl** [kevinconway/rpmvenv#28]
Hi,

With rpmvenv, what would be the best way to prevent overwriting config files during package upgrade ?
<br>
I found this link with instructions, but I don't know if those can be used with rpmvenv

http://www-uxsup.csx.cam.ac.uk/~jw35/docs/rpm_config.html

**Comment by kevinconway** [comment]
This is a good question. I didn't consider this scenario because most of my teams have used some kind of configuration management stack, like chef or puppet, to manage the configuration files. Even so, I think having the option of using the `%config` file directive would be a good thing.

I don't believe there is currently a way to do this. However, we can add an extension to the `files` sub-package that allows us to define configs in the JSON config file for rpmvenv. It's very likely we should do the same thing with `%doc`.

If this is something you need ASAP I would encourage you to put up a pull request that adds the new extension. You can use https://github.com/kevinconway/rpmvenv/blob/master/rpmvenv/extensions/files/extras.py as an example.

**Comment by kevinconway** [comment]
Version 0.15.0 on PyPi now includes support for applying the `%config` and `%doc` options to files.
