### ISSUE TITLE
Unable to relocate virtualenv because of unicode issue

### ISSUE THREAD

**Issue by 23jodys** [kevinconway/rpmvenv#65]
```
rpmvenv rpmvenv.json
...
+ venvctrl-relocate --source=/tmp/rpmvenv126rjt63/BUILDROOT/archer-dlbcl_web-1.0.8-1_.el7.centos.x86_64//usr/share/archer/venv//dlbcl_web --destination=//usr/share/archer/venv//dlbcl_web
Traceback (most recent call last):
  File "/usr/bin/venvctrl-relocate", line 9, in <module>
    load_entry_point('venvctrl==0.2.1', 'console_scripts', 'venvctrl-relocate')()
  File "/usr/lib/python3.4/site-packages/venvctrl/cli/relocate.py", line 53, in main
    relocate(args.source, args.destination, args.move)
  File "/usr/lib/python3.4/site-packages/venvctrl/cli/relocate.py", line 24, in relocate
    venv.relocate(destination)
  File "/usr/lib/python3.4/site-packages/venvctrl/venv/relocate.py", line 35, in relocate
    os.path.join(destination, 'bin', 'python')
  File "/usr/lib/python3.4/site-packages/venvctrl/venv/base.py", line 178, in shebang
    self.writeline(new_shebang, 0)
  File "/usr/lib/python3.4/site-packages/venvctrl/venv/base.py", line 86, in writeline
    for count, new_line in enumerate(file_handle):
  File "/usr/lib64/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 157: ordinal not in range(128)
error: Bad exit status from /var/tmp/rpm-tmp.BZi8gI (%install)
```

It looks like the specific issue is from `boto3`. There are some files in that distribution that are UTF-8.

The underlying problem appears to be in `venvctrl-relocate` when it attempts to shebang replaces files. It looks like this section is not aware of encoding or decoding.

It seems like the problem is best fixed there, but it is a lot easier to reproduce in `rpmvenv`, so I thought'd I'd open the bug here.

I think I can make a simple fix in `venvctrl`, but I was curious if you had any better insight on how you want to deal with this.

I made a simple docker image that can replicate this problem reliably, https://github.com/23jodys/venvctrl_bug_report/tree/master.

Thanks!

**Comment by kevinconway** [comment]
Hi there!

Thanks for opening an issue! I'm really appreciative of the repro steps and the docker file to automate reproducing this. That makes things so much easier. I pulled down your sample repo and was able to see the issue in action.

My first reaction is that we're fighting a set of defaults. The default file encoding for CentOS is ASCII and the default behavior of Python is to open all files using the system encoding. I'm open to modifying `venvctrl` if we need to but I'd like to explore some other options first.

The project already makes a strong assumption that the text being consumed is UTF-8 (or a valid subset such as ASCII). For example, we don't encounter this issue when reading the shebangs because it's handled as a binary stream of data that is later decoded using UTF-8 (https://github.com/kevinconway/venvctrl/blob/master/venvctrl/venv/base.py#L151). Because of this, I think there's a decent argument to make that the correct behavior of https://github.com/kevinconway/venvctrl/blob/master/venvctrl/venv/base.py#L70 is to use `open(self.path, "r", encoding="utf-8")` rather than relying on the system default. My larger concern with that approach is that it is hard to estimate how that might impact existing users. I try to be extra cautious about changes to `rpmvenv` and `venvctrl` because they tend to support automating installs in older systems.

All of that is context around the suggestion that it might be easier to change the system encoding or, more likely, override the system encoding only for the rpm build. For example, the docker file you linked executes with:
```bash
docker run -it -v `pwd`:/mnt -w /mnt bug_report:latest bash -c "rpmvenv --verbose rpmvenv.json"
```
If you add an ENV override for the locale with
```bash
docker run -e 'LC_ALL=en_US.UTF-8' -it -v `pwd`:/mnt -w /mnt bug_report:latest bash -c "rpmvenv --verbose rpmvenv.json"
```
then the build finishes without errors because Python will adopt whichever encoding is set for the system.

Let me know if this is a viable solution for you. If not then we can think in more depth around the impacts of changing the encoding used by `venvctrl`.

**Comment by 23jodys** [comment]
Thanks @kevinconway, your suggestion of overriding the default encoding works perfectly for our issue. Would you like me to update the README.md with a mention of this workaround?
