### ISSUE TITLE
Ability to specify Vendor and Packager

### ISSUE THREAD

**Issue by fgimian** [kevinconway/rpmvenv#73]
Hey there, cool project!

I can't see a way to specify the **Vendor** and **Packager** tags.  You can see the tags detailed here: http://ftp.rpm.org/max-rpm/s1-rpm-inside-tags.html

Thanks
Fotis

**Comment by kevinconway** [comment]
The project currently does not have support for these two tags. I suspect this is because few folks are using this library to create publicly distributed RPM packages. I believe most people who use this project do so to automate builds within their company or organization so the need to provide vendor and packager data has not been pressing.

If you would like to add support for these tags then it should be a fairly straightforward addition to the `core` plugin (https://github.com/kevinconway/rpmvenv/blob/master/rpmvenv/extensions/core.py). This is where all of the top-level RPM specification tags are handled and would be the best place to add the vendor and packager tags.

**Comment by fgimian** [comment]
Thanks so much for the reply, I may look at contributing in the future.  In the meantime, I ended up going with a pure spec file for my project which worked out well 😄 

Have a great weekend
Fotis

**Comment by kevinconway** [comment]
If you find time to make a PR then please feel free to reopen this issue. I'm going to close it out for now since you have something else that works for you.
