### ISSUE TITLE
Ability to set mode on extra files

### ISSUE THREAD

**Issue by fgimian** [kevinconway/rpmvenv#74]
Currently it seems impossible to set the file mode on extra files.  In many cases, config files for example should have more tight permissions (say 0600) and this currently doesn't seem possible with rpmvenv.

Cheers
Fotis

**Comment by kevinconway** [comment]
@fgimian Correct, it is not currently accounted for as a feature. The project supports setting the user and group owner for a file but not directly modifying the file permissions. There are a few ways to achieve what you're suggesting, I think.

The most straightforward method is to set the file permissions in the package source since the permissions are preserved during the build. For example, if the configuration file permissions are `0600` in the source repository then the installed file will also have `0600` permissions.

A second option is using a post-install script to modify the permissions of any installed files. Granted, this is not the ideal solution since RPM has support for setting file permissions using `%attr()` but this may be an effective workaround in lieu of changing any code.

A third option, if you have the time and desire, is to make a PR that adds the ability to set file permissions. The most likely place this would fit is the `file_extras` plugin at https://github.com/kevinconway/rpmvenv/tree/master/rpmvenv/extensions/files. It currently accepts a dictionary for each file to copy that could be extended to allow defining the file permissions.

**Comment by fgimian** [comment]
Thanks a lot for the reply 😄

**Comment by kevinconway** [comment]
I'll assume from your comment in #73 that you have something that does what you need. If this is not correct then please reopen this issue. I'm happy to chat about this more.
