### ISSUE TITLE
Error from confpy: "AttributeError: can't set attribute"

### ISSUE THREAD

**Issue by WilliamDEdwards** [kevinconway/rpmvenv#80]
Hi!

I am attempting to use `rpmvenv` for the first time.

This is my config file:

```
[root@cltest virtualenv]# cat venv.json
{
  "extensions": {
    "enabled": [
      "python_venv"
    ]
  },
  "core": {
    "group": "Application/System",
    "name": "iSPyAPI",
    "description": "Internal WebOps platform API",
    "license": "Copyright",
    "version": "1.0.0"
  },
  "python_venv": {
    "name": "env",
    "path": "/opt/ispyapi",
    "cmd": "virtualenv",
    "flags": ["--always-copy"],
    "name": "ispyapi",
    "path": "/usr/share/python-ispyapi",
    "python": "python3.7",
    "require_setup_py": true,
    "requirements": ["requirements.txt"]
  }
}
```

However, when attempting to build the RPM, I get an error:

```
[root@cltest virtualenv]# rpmvenv venv.json
Traceback (most recent call last):
  File "/usr/local/bin/rpmvenv", line 11, in <module>
    load_entry_point('rpmvenv==0.23.0', 'console_scripts', 'rpmvenv')()
  File "/usr/local/lib/python3.6/site-packages/rpmvenv/cli.py", line 113, in main
    strict=True,
  File "/usr/local/lib/python3.6/site-packages/confpy/parser.py", line 218, in parse_options
    config=configuration_from_paths(paths=files, strict=strict),
  File "/usr/local/lib/python3.6/site-packages/confpy/parser.py", line 75, in configuration_from_paths
    cfg = configfile_from_path(path, strict=strict).config
  File "/usr/local/lib/python3.6/site-packages/confpy/loaders/base.py", line 76, in config
    setattr(name, item, value)
  File "/usr/local/lib/python3.6/site-packages/confpy/core/namespace.py", line 139, in __setattr__
    return object.__setattr__(self, name, value)
AttributeError: can't set attribute
```

Do you have any idea why that is? I feel like something is wrong with my config file, but I'm not sure what it is when comparing mine to the documentation.

**Comment by kevinconway** [comment]
@WilliamDEdwards It seems to be two issues and neither presents a good error message.

The first issue is that `description` is not a configuration field of the `core` namespace. This, unfortunately, raises a generic `AttributeError` rather than reporting the failed key. This is something that `confpy` should handle better. The expected field in `core` is `summary` rather than `description`. The `description` field is available in the `blocks` extension and must be set to an array of strings where each item is a separate line in the final spec.

If you convert the `description` field to `summary` then it will get to the point of building an RPM. This may still fail depending on which version of RPM you are using during the build. It appears recent versions, at least, require a `description` attribute in the spec file which can only be done, currently, through the `blocks` extension. I don't recall this always being a requirement or `description` _would_ be in the `core` extension because that was meant to represent all required attributes of a package.

An example working config:

```json
{
  "extensions": {
    "enabled": [
      "python_venv",
      "blocks"
    ]
  },
  "core": {
    "group": "Application/System",
    "name": "iSPyAPI",
    "summary": "Internal WebOps platform API",
    "license": "Copyright",
    "version": "1.0.0"
  },
  "python_venv": {
    "name": "env",
    "path": "/opt/ispyapi",
    "cmd": "virtualenv",
    "flags": ["--always-copy"],
    "name": "ispyapi",
    "path": "/usr/share/python-ispyapi",
    "python": "python3.7",
    "require_setup_py": true,
    "requirements": ["requirements.txt"]
  },
  "blocks": {
    "description": ["Internal WebOps platform API"]
  }
}
```

A tangential note, the example you posted has several fields, like `name` and `path`, present twice in the same namespace. This will work but the determination of which is actually selected is not defined and at the mercy of the JSON parser implementation choices.

I'll close the issue but re-open if this does not resolve the issue for you.
