### ISSUE TITLE
The stderr was: error: Package has no %description from CLI

### ISSUE THREAD

**Issue by patsevanton** [kevinconway/rpmvenv#85]
Hello!
Thanks for rpmvenv!

I try build rpm for Python package with option --blocks_desc="msgpack"
But get error `The stderr was: error: Package has no %description`

```
echo "{}" > conf.json && LC_ALL=en_US.UTF-8 rpmvenv conf.json --core_name="msgpack" --core_version="0.6.1" --core_license="MIT" --core_summary="msgpack" --blocks_desc="msgpack"
There was an error generating the RPM.
The exit code was: 1.
The rpmbuild command was: rpmbuild -ba --define='_topdir /tmp/rpmvenv3ECQBe' /tmp/rpmvenv3ECQBe/SOURCES/package.spec.
The stderr was: error: Package has no %description: msgpack
.
The stdout was: .
```

**Comment by kevinconway** [comment]
I see now. The issue is that there are many flags that must be used for this to work without a file. I apologize for the issue. I think you are the first to try this without a JSON file.

Each plugin must be enabled using `--extensions_enabled="one,two,three"`. For example, you need `--extensions_enabled="blocks,python_venv"` at minimum. Then you must give flags for each plugin to configure it. Here is a command that I think will work:

```bash
echo "{}" > conf.json && \
rpmvenv conf.json \
  --core_name="msgpack" \
  --core_version="0.6.1" \
  --core_license="MIT" \
  --core_summary="msgpack" \
  --extensions_enabled="blocks,python_venv" \
  --python_venv_name="msgpack" \
  --blocks_desc="msgpack"
```
All other options from https://github.com/kevinconway/rpmvenv#customizing can then be added as a flag using the pattern `--<extension>_<option="<value>"`. For example, you can change the install path with `--python_venv_path="/path/where/install"`. Lists, or arrays, are defined in flags as comma separated. For example, `--blocks_desc="line one,line two,line three"` and `--extensions_enabled="blocks.python_venv,file_extras"`.

**Comment by patsevanton** [comment]
Work

```
echo "{}" > conf.json && LC_ALL=en_US.UTF-8 rpmvenv conf.json --core_name="msgpack" --core_version="0.6.1" --core_license="MIT" --core_summary="msgpack" --extensions_enabled="blocks,python_venv" --python_venv_name="msgpack" --blocks_desc="msgpack"
```

ImportError: No module named zipp - issue of virtualenv.

Thanks!
