### ISSUE TITLE
Virtualenv activate scripts contain BUILDROOT causing build to fail

### ISSUE THREAD

**Issue by bryanapperson** [kevinconway/rpmvenv#87]
Using either the tool, or the spec file it generates, the `%{venv_dir}/bin/activate*` files contain the full build root path which causes the rpm build to fail. Adding `find %{venv_dir}/bin -type f | xargs sed -i "s#%{buildroot}##g"` at the end of `%install` fixes the issue.

Python: 3.7.4
Pip: 20.0.2
Virtualenv: 20.0.18

**Comment by kevinconway** [comment]
Can you also provide which version of `rpmvenv` and a sample config or spec file?

The activators, and other bin files, are supposed to be rewritten by [venvctrl](https://github.com/kevinconway/venvctrl/blob/master/venvctrl/venv/relocate.py) and it's handled that pretty well for the last few years. If it's regressed recently then they may have added a new activate script since `venvctrl` only handles a [specified list of scripts](https://github.com/kevinconway/venvctrl/blob/master/venvctrl/venv/base.py#L268).

**Comment by kevinconway** [comment]
Looks like someone else hit this issue. Appears related to a virtualenv change that recently shipped in one of the `20.0.x` patch versions. I'm going to combine the issues. The other open issue has more debug information so I'll move the conversation there.

https://github.com/kevinconway/rpmvenv/issues/88

**Comment by bryanapperson** [comment]
Thanks for the fast resolution!
