### ISSUE TITLE
How use constraints with rpmvenv ?

### ISSUE THREAD

**Issue by patsevanton** [kevinconway/rpmvenv#97]
Hello! Thanks for rpmvenv !
I try pack apache-airflow to rpm with all dependencies

```
sudo yum -y install epel-release rpmdevtools wget
sudo yum -y install python3-pip
pip3 install --user rpmvenv
pip3 install --user virtualenv
wget https://raw.githubusercontent.com/apache/airflow/constraints-1.10.12/constraints-3.6.txt
mv constraints-3.6.txt requirements.txt


echo "{}" > conf.json && \
LC_ALL=en_US.UTF-8 rpmvenv conf.json \
  --core_name="apache-airflow" \
  --core_version="1.10.14" \
  --core_license="ASL 2.0" \
  --core_summary="apache-airflow" \
  --extensions_enabled="blocks,python_venv" \
  --python_venv_name="apache-airflow" \
  --blocks_desc="apache-airflow" \
  --python_venv_require_setup_py="false"
```

Error

`mysqlclient_355a493b594d461ab5d88bfdbf320ed5/setup_posix.py", line 28, in mysql_config\n        raise EnvironmentError("%s not found" % (mysql_config.path,))\n    OSError: mysql_config not found\n    ----------------------------------------\nERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\nerror: Bad exit status from /var/tmp/rpm-tmp.XDwsOJ (%install)\n    Bad exit status from /var/tmp/rpm-tmp.XDwsOJ (%install)\n'.
`

**Comment by kevinconway** [comment]
I think `rpmvenv` is working as expected but the constraints file you are using includes `mysqlclient` which depends on system packages. https://pypi.org/project/mysqlclient/ has installation instructions. I believe you must first install `mysql-devel` along with `epel-release rpmdevtools wget` for it to work.

Since `mysqlclient` depends on a system package you may still have trouble if the machine you deploy to is missing the same packages or if it has different versions of the packages installed. One way to manage this is by using the `--core_dependencies` flag to add any required system dependencies. Any item in that list will be automatically installed by `rpm` before installing your `virtualenv`.

One last note, you are installing the `requirements.txt` from the apache airflow project but are not installing airflow. You need to add something like `apache-airflow==2.0.0` to you requirements.txt in order to also install airflow.

**Comment by patsevanton** [comment]
constraints-3.6.txt is recomendation for version.
Thanks for help!
